{% set name = "pyqt-stubs" %}
{% set version = "5.15.6.0" %}
{% set pypi_name = "PyQt5-stubs" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 91270ac23ebf38a1dc04cd97aa852cd08af82dc839100e5395af1447e3e99707

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyqt ~=5.15.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/python-qt-tools/PyQt5-stubs
  summary: Mypy stubs for the PyQt5 framework
  description: |
    The stub files released within the PyQt5 packages have been modified to allow using them for type-checking via mypy.
    Improvements over the default stubs include:
    Signals are properly typed as signals and not as methods
    QFlags derived classes correctly support all combination operations
    Many methods accepting an optional None have been annotated so
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoechenberger
